# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('contenido', models.TextField()),
                ('fechacreado', models.DateTimeField(auto_now_add=True)),
                ('fechainicio', models.DateTimeField(auto_now_add=True)),
                ('fechafinal', models.DateTimeField(auto_now_add=True)),
                ('fechamodificado', models.DateTimeField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueo', models.BooleanField(default=True)),
                ('acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Tipoacceso')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fechacreado'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Categoria'),
        ),
    ]
