# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fechacreado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='fechainicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='fechamodificado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
