# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140)),
                ('menu', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('contenido', models.TextField()),
                ('fechacreado', models.DateTimeField(auto_now_add=True)),
                ('fechainicio', models.DateTimeField(auto_now=True)),
                ('fechafinal', models.DateTimeField()),
                ('fechamodificado', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fechacreado'],
            },
        ),
        migrations.CreateModel(
            name='Tipoacceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Tipoacceso'),
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Tipoacceso'),
        ),
    ]
