# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=140)),
                ('imptotal', models.IntegerField(blank=True, null=True)),
                ('impmade', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('clickurl', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('custombannercode', models.TextField(blank=True, max_length=2048, null=True)),
                ('sticky', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
                ('metakey', models.TextField(blank=True, null=True)),
                ('own_prefix', models.IntegerField(blank=True, null=True)),
                ('metakey_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_type', models.IntegerField(blank=True, null=True)),
                ('track_clicks', models.IntegerField(blank=True, null=True)),
                ('track_impressions', models.TextField(blank=True, null=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_out_time', models.DateTimeField(auto_now_add=True)),
                ('publish_up', models.DateTimeField(auto_now_add=True)),
                ('publish_down', models.DateTimeField(auto_now_add=True)),
                ('reset', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('alias', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('track_type', models.IntegerField(default=0)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('banner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Banner')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='catid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Banner_categoria'),
        ),
        migrations.AddField(
            model_name='banner',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
