# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20170807_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='posts',
        ),
    ]
